---
title: "Elecciones presidenciales Chile 1989-2017"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(plotly)
library(chilemapas)
library(shiny)
```


```{r bases}
cod <- readxl::read_xlsx('../dashboard_elecciones/inputs/codigo_comunas.xlsx') %>% 
  janitor::clean_names() %>% 
  rename('codigo_comuna' = cut_codigo_unico_territorial) %>% 
  mutate(comuna = chartr('áéíóúü','aeiouu',tolower(nombre)))

df_elec <- readRDS('../dashboard_elecciones/inputs/base_elec.rds') %>% 
  janitor::clean_names() %>% 
  mutate(comuna = chartr('áéíóúü','aeiouu',tolower(comuna)),
         comuna = case_when((comuna == 'aisen') ~ 'aysen',
                            (comuna == 'calera') ~ 'la calera',
                            (comuna == 'marchigue') ~ 'marchihue',
                            (comuna == 'tiltil') ~ 'til til',
                            TRUE ~ comuna))

df_elec2 <- left_join(df_elec,
                      cod,
                      by = 'comuna') %>% 
  select(-provincia.y)

```


```{r limpieza base}
# Incorporar nuevas regiones
df_elec2 <- df_elec2 %>% 
  mutate(id_region = (ifelse((comuna %in% c('corral', 'futrono', 'la union', 'lago ranco', 'lanco', 'los lagos', 'mafil', 'mariquina', 'paillaco', 'panguipulli', 'rio bueno', 'valdivia')),14,id_region)),
         id_region = (ifelse((comuna %in% c('arica','camarones','general lagos','putre')),15,id_region)))

# Diferenciar entre elecciones (primera y segunda vuelta no siempre fueron en años diferentes)
df_elec2 <- df_elec2 %>% 
  mutate(vuelta = case_when((votacion_presidencial == 'UNICA VOTACIÓN')~ '1',
                            (votacion_presidencial == 'PRIMERA VOTACIÓN')~ '1',
                            (votacion_presidencial == 'SEGUNDA VOTACIÓN')~ '2',
                            TRUE ~ NA_character_),
         ano_de_eleccion = case_when((ano_de_eleccion == 2000)~1999,
                                     (ano_de_eleccion == 2006)~2005,
                                     (ano_de_eleccion == 2010)~2009,
                                     TRUE ~ ano_de_eleccion),
         eleccion = paste0(vuelta,'-',ano_de_eleccion))

# Extracción de nulos y blancos
df_elec2 <- df_elec2 %>% 
  filter(candidato_a != 'VOTOS NULOS',
         candidato_a != 'VOTOS EN BLANCO')
```


```{r cálculos}
# Cálculo de total de votos por candidato por comuna y región
df_elec_calc <- df_elec2 %>% 
  group_by(codigo_comuna,eleccion) %>% 
  mutate(tot_com = sum(votos_totales),
         por_com = (votos_totales/tot_com)) %>% 
  group_by(candidato_a,codigo_comuna,eleccion) %>% 
  mutate(tot_cand_com = round(sum(por_com),3)) %>% 
  ungroup() %>% 
  group_by(eleccion) %>% 
  mutate(tot_nac = sum(votos_totales)) %>% 
  group_by(candidato_a,eleccion) %>% 
  mutate(votos_cand_nac = sum(votos_totales),
         tot_cand_nac = round(votos_cand_nac/tot_nac,3)) %>% 
  ungroup()

# Agrupación por coaliciones
df_elec_calc <- df_elec_calc %>% 
  mutate(coalicion =  case_when((candidato_a %in% c('HERNAN BUCHI', 'ARTURO ALESSANDRI', 'JOAQUIN LAVIN', 'SEBASTIAN PIÑERA', 'EVELYN MATTHEI FORNET', 'SEBASTIAN PIÑERA ECHENIQUE'))~'Chile Vamos y anteriores',
                                    (candidato_a %in% c('PATRICIO AYLWIN', 'EDUARDO FREI', 'RICARDO LAGOS', 'MICHELLE BACHELET', 'MICHELLE BACHELET JERIA', 'CAROLINA GOIC BOROEVIC', 'ALEJANDRO  GUILLIER ALVAREZ')~ 'Nueva Mayoría y anteriores'),
                                    TRUE ~ 'Otros'))

# Cálculo de porcentajes por coalición por comuna
df_elec_com <- df_elec_calc %>%
  count(eleccion,codigo_comuna,comuna,candidato_a,tot_cand_com,coalicion) %>% 
  group_by(codigo_comuna,coalicion,eleccion) %>% 
  mutate(tot_coal_com = sum(tot_cand_com)) %>% 
  select(-n)

# Cálculo de porcentajes por coalición nacional
df_elec_nac <- df_elec_calc %>%
  count(eleccion,candidato_a,tot_cand_nac,coalicion) %>% 
  group_by(coalicion,eleccion) %>% 
  mutate(tot_coal_nac = sum(tot_cand_nac)) %>% 
  count(eleccion,coalicion,tot_coal_nac) %>% 
  select(-n)

df_elec_nac$eleccion <- factor(df_elec_nac$eleccion, levels = c('1-1989',
                                                                '1-1993',
                                                                '1-1999',
                                                                '2-1999',
                                                                '1-2005',
                                                                '2-2005',
                                                                '1-2009',
                                                                '2-2009',
                                                                '1-2013',
                                                                '2-2013',
                                                                '1-2017',
                                                                '2-2017'))

# Unión con chilemapas
mapa <- mapa_comunas %>% 
  left_join(df_elec_com, by = 'codigo_comuna') %>% 
  mutate(region = as.numeric(codigo_region))
```

# Datos generales

## Sidebar {data-width=200 .sidebar}

```{r}
selectInput('region', label = 'Región:',
            choices = c(15,1:9,14,10,11:13), 
            selected = '13')
            
selectInput('coalicion', label = 'Coalición:',
            choices = c('Chile Vamos y anteriores',
                        'Nueva Mayoría y anteriores', 
                        'Otros'), 
            selected = 'Otros')

selectInput('eleccion', label = 'Elección:',
            choices = c('1-1989',
                        '1-1993',
                        '1-1999',
                        '2-1999',
                        '1-2005',
                        '2-2005',
                        '1-2009',
                        '2-2009',
                        '1-2013',
                        '2-2013',
                        '1-2017',
                        '2-2017'), 
            selected = '1-1989')

map2_df <- reactive({
  req(input$eleccion)
  mapa %>%
    filter(region == input$region, 
           coalicion == input$coalicion,
           eleccion == input$eleccion)
})


map3_df <- reactive({
  req(input$eleccion)
  mapa %>%
    filter(eleccion == input$eleccion) %>% 
    count(candidato_a,codigo_region) %>% 
    tidyr::spread(candidato_a,n) %>% 
    ncol()-1
})

map4_df <- reactive({
  req(input$coalicion)
  df_elec_nac %>%
    filter(coalicion == input$coalicion)
})

```

## Column {data-width=400}

### Mapa

```{r}
renderPlotly({
uno <- map2_df () %>% 
    filter(region == input$region,
           coalicion == input$coalicion,
           eleccion == input$eleccion) %>%
  mutate(total = tot_coal_com*100) %>% 
  ggplot() +
  geom_sf(aes(fill = total, geometry = geometry),size = 0.01) +
  geom_sf_text(aes(geometry = geometry,label = comuna), size = 0.1, colour = 'black',alpha = 0.1)+
  theme(axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())+
  colorspace::scale_fill_continuous_sequential()+
  labs(fill = '%')

ggplotly(uno)
})
```

## Column {data-width=350}

### Número de candidatos en elección seleccionada
```{r}
renderValueBox({
  valueBox(prettyNum((map3_df())),
         icon = 'fa-handshake')
})
```

### Evolución de la votación de la coalición seleccionada

```{r}
renderPlot({
map4_df() %>% 
    filter(coalicion == input$coalicion) %>% 
    ggplot(aes(x = eleccion, y = tot_coal_nac, group = 1))+
    geom_line() +
    geom_text(aes(label = scales::percent(tot_coal_nac)),size = 2.5, nudge_y = 0.02) +
  theme(axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())+
  labs(x = 'Elección')
})
```


```{r ult 5 elec}
df_map <- mapa %>% 
  group_by(eleccion,comuna,coalicion) %>% 
  sjmisc::add_id() %>% 
  filter(ID == 1) %>% 
  select(coalicion,geometry,tot_coal_com,eleccion,comuna) %>% 
  ungroup() %>% 
  group_by(eleccion,comuna) %>% 
  mutate(ganador = (max(tot_coal_com)),
         aux = (ganador == tot_coal_com),
         gan_f = ifelse((aux == TRUE),coalicion,0)) %>% 
  filter(gan_f != 0)
```


# Comparación nacional entre elecciones

## Sidebar {data-width=100 .sidebar}

```{r}
selectInput('eleccion_1', label = 'Elección (primera):',
            choices = c('1-1989',
                        '1-1993',
                        '1-1999',
                        '2-1999',
                        '1-2005',
                        '2-2005',
                        '1-2009',
                        '2-2009',
                        '1-2013',
                        '2-2013',
                        '1-2017',
                        '2-2017'),
            selected = '1-1989')

selectInput('eleccion_2', label = 'Elección (segunda):',
            choices = c('1-1989',
                        '1-1993',
                        '1-1999',
                        '2-1999',
                        '1-2005',
                        '2-2005',
                        '1-2009',
                        '2-2009',
                        '1-2013',
                        '2-2013',
                        '1-2017',
                        '2-2017'),
            selected = '1-1993')

selectInput('eleccion_3', label = 'Elección (tercera):',
            choices = c('1-1989',
                        '1-1993',
                        '1-1999',
                        '2-1999',
                        '1-2005',
                        '2-2005',
                        '1-2009',
                        '2-2009',
                        '1-2013',
                        '2-2013',
                        '1-2017',
                        '2-2017'),
            selected = '1-1999')

map5_df <- reactive({
  req(input$eleccion_1)
  df_map %>%
    filter(eleccion == input$eleccion_1)
})

map6_df <- reactive({
  req(input$eleccion_2)
  df_map %>%
    filter(eleccion == input$eleccion_2)
})

map7_df <- reactive({
  req(input$eleccion_3)
  df_map %>%
    filter(eleccion == input$eleccion_3)
})


```

## Column {data-width=200}

```{r}
renderPlot({
map5_df() %>% 
    filter(eleccion == input$eleccion_1) %>% 
    ggplot()+
  stat_sf_coordinates(aes(geometry = geometry, color = gan_f))+
  theme(axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())+
  coord_sf(xlim = c(-80, -60),expand = TRUE)+
  labs(color = '')+
  scale_color_manual(values = c('blue','red','white'), breaks = c('Chile Vamos y anteriores', 'Nueva Mayoría y anteriores','Otros'))
    
})

```

## Column {data-width=200}

```{r}
renderPlot({
map6_df() %>% 
    filter(eleccion == input$eleccion_2) %>% 
    ggplot()+
  stat_sf_coordinates(aes(geometry = geometry, color = gan_f))+
  theme(axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())+
  coord_sf(xlim = c(-80, -60),expand = TRUE)+
  labs(color = '')+
  scale_color_manual(values = c('blue','red','white'), breaks = c('Chile Vamos y anteriores', 'Nueva Mayoría y anteriores','Otros'))
    
})
```


## Column {data-width=200}

```{r}
renderPlot({
map7_df() %>% 
    filter(eleccion == input$eleccion_3) %>% 
    ggplot()+
  stat_sf_coordinates(aes(geometry = geometry, color = gan_f))+
  theme(axis.line.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank(),
        axis.line.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())+
  coord_sf(xlim = c(-80, -60),expand = TRUE)+
  labs(color = '')+
  scale_color_manual(values = c('blue','red','white'), breaks = c('Chile Vamos y anteriores', 'Nueva Mayoría y anteriores','Otros'))
    
})
```
